## To change the default prefix, uncomment and update 'v'
# unbind C-b
# set -g prefix C-v
# bind C-v send-prefix

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g mode-keys vi
set -g default-shell /bin/zsh
set -g default-command "exec /bin/zsh -l"

bind '|' split-window -v -c "#{pane_current_path}" # default is %
bind '\' split-window -h -c "#{pane_current_path}" # default is "
bind x kill-pane

run '~/.tmux/plugins/tpm/tpm'
set -g mode-keys vi
set -g set-clipboard on
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
bind-key -T copy-mode-vi MouseDragEnd1Pane send -X copy-pipe-and-cancel "pbcopy"

set -g status-style "bg=colour214,fg=black"

run '~/.tmux/plugins/tpm/tpm'